"""Limitation, warning, and blocker code enumerations for Cardre readiness.

Centralises all codes used by check.py and collector.py into a StrEnum,
eliminating bare-string duplication and enabling exhaustiveness checks.
"""

from __future__ import annotations

from enum import StrEnum


class LimitationCode(StrEnum):
    """All recognised limitation/warning/blocker codes in one enum."""

    # --- Blockers ---
    TARGET_BRANCH_NOT_FOUND = "TARGET_BRANCH_NOT_FOUND"
    TARGET_BRANCH_INCOMPLETE = "TARGET_BRANCH_INCOMPLETE"
    CHAMPION_ASSIGNMENT_MISSING = "CHAMPION_ASSIGNMENT_MISSING"
    CHAMPION_BRANCH_INCOMPLETE = "CHAMPION_BRANCH_INCOMPLETE"
    MISSING_REQUIRED_CANONICAL_STEP = "MISSING_REQUIRED_CANONICAL_STEP"
    MISSING_WOE_IV_EVIDENCE = "MISSING_WOE_IV_EVIDENCE"
    MISSING_FINAL_SCORECARD = "MISSING_FINAL_SCORECARD"
    MISSING_MODEL_COEFFICIENTS = "MISSING_MODEL_COEFFICIENTS"
    MISSING_SCORE_SCALING = "MISSING_SCORE_SCALING"
    MISSING_TRAIN_VALIDATION_METRICS = "MISSING_TRAIN_VALIDATION_METRICS"
    MISSING_RUN_MANIFEST = "MISSING_RUN_MANIFEST"
    MISSING_PATHWAY = "MISSING_PATHWAY"
    MANUAL_BINNING_NOT_REVIEWED = "MANUAL_BINNING_NOT_REVIEWED"
    ARTIFACT_HASH_UNRESOLVED = "ARTIFACT_HASH_UNRESOLVED"
    RUN_NOT_SUCCEEDED = "RUN_NOT_SUCCEEDED"
    CANONICAL_MANIFEST_UNREADABLE = "CANONICAL_MANIFEST_UNREADABLE"
    CANONICAL_MANIFEST_MISSING = "CANONICAL_MANIFEST_MISSING"
    NON_MONOTONIC_WOE_CHAMPION = "NON_MONOTONIC_WOE_CHAMPION"
    NO_OOT_SAMPLE_CHAMPION = "NO_OOT_SAMPLE_CHAMPION"
    WOE_EVIDENCE_READ_FAILURE = "WOE_EVIDENCE_READ_FAILURE"

    # --- Warnings ---
    NO_OOT_SAMPLE = "NO_OOT_SAMPLE"
    NO_TEST_SAMPLE = "NO_TEST_SAMPLE"
    NO_CHAMPION_ASSIGNMENT = "NO_CHAMPION_ASSIGNMENT"
    MISSING_CHAMPION_RATIONALE = "MISSING_CHAMPION_RATIONALE"
    NO_CHALLENGER_COMPARISON = "NO_CHALLENGER_COMPARISON"
    TARGET_BRANCH_NOT_CHAMPION = "TARGET_BRANCH_NOT_CHAMPION"
    INHERITED_BRANCH_EVIDENCE = "INHERITED_BRANCH_EVIDENCE"
    INHERITED_BASELINE_EVIDENCE = "INHERITED_BASELINE_EVIDENCE"
    NO_CUTOFF_ANALYSIS = "NO_CUTOFF_ANALYSIS"
    NO_MANUAL_BINNING_STEP_ON_BRANCH = "NO_MANUAL_BINNING_STEP_ON_BRANCH"
    MISSING_MANUAL_INTERVENTION_REASON = "MISSING_MANUAL_INTERVENTION_REASON"
    MISSING_MODELLING_METADATA = "MISSING_MODELLING_METADATA"
    SMOOTHING_APPLIED = "SMOOTHING_APPLIED"
    ZERO_CELL_POLICY_USED = "ZERO_CELL_POLICY_USED"
    WOE_SUMMARY_USED_INSTEAD_OF_EVIDENCE = "WOE_SUMMARY_USED_INSTEAD_OF_EVIDENCE"
    MISSING_VARIABLE_CLUSTERING_EVIDENCE = "MISSING_VARIABLE_CLUSTERING_EVIDENCE"
    PDF_OUT_OF_SCOPE = "PDF_OUT_OF_SCOPE"
    MANUAL_BINNING_REVIEWED_WITH_WARNINGS = "MANUAL_BINNING_REVIEWED_WITH_WARNINGS"

    # --- Collector block codes (not in readiness BLOCKER_CODES) ---
    MISSING_RUN_MANIFEST_COLLECTOR = "MISSING_RUN_MANIFEST"

    @classmethod
    def blocker_codes(cls) -> set[LimitationCode]:
        """Return the set of codes that represent blockers."""
        return {
            cls.TARGET_BRANCH_NOT_FOUND,
            cls.TARGET_BRANCH_INCOMPLETE,
            cls.CHAMPION_ASSIGNMENT_MISSING,
            cls.CHAMPION_BRANCH_INCOMPLETE,
            cls.MISSING_REQUIRED_CANONICAL_STEP,
            cls.MISSING_WOE_IV_EVIDENCE,
            cls.MISSING_FINAL_SCORECARD,
            cls.MISSING_MODEL_COEFFICIENTS,
            cls.MISSING_SCORE_SCALING,
            cls.MISSING_TRAIN_VALIDATION_METRICS,
            cls.MISSING_RUN_MANIFEST,
            cls.MISSING_PATHWAY,
            cls.MANUAL_BINNING_NOT_REVIEWED,
            cls.ARTIFACT_HASH_UNRESOLVED,
            cls.RUN_NOT_SUCCEEDED,
            cls.NON_MONOTONIC_WOE_CHAMPION,
            cls.NO_OOT_SAMPLE_CHAMPION,
            cls.WOE_EVIDENCE_READ_FAILURE,
            cls.CANONICAL_MANIFEST_UNREADABLE,
        }

    @classmethod
    def warning_codes(cls) -> set[LimitationCode]:
        """Return the set of codes that represent warnings."""
        return {
            cls.NO_OOT_SAMPLE,
            cls.NO_TEST_SAMPLE,
            cls.NO_CHAMPION_ASSIGNMENT,
            cls.NO_MANUAL_BINNING_STEP_ON_BRANCH,
            cls.MISSING_CHAMPION_RATIONALE,
            cls.NO_CHALLENGER_COMPARISON,
            cls.TARGET_BRANCH_NOT_CHAMPION,
            cls.INHERITED_BRANCH_EVIDENCE,
            cls.INHERITED_BASELINE_EVIDENCE,
            cls.NO_CUTOFF_ANALYSIS,
            cls.MISSING_MANUAL_INTERVENTION_REASON,
            cls.MISSING_MODELLING_METADATA,
            cls.SMOOTHING_APPLIED,
            cls.ZERO_CELL_POLICY_USED,
            cls.WOE_SUMMARY_USED_INSTEAD_OF_EVIDENCE,
            cls.MISSING_VARIABLE_CLUSTERING_EVIDENCE,
            cls.PDF_OUT_OF_SCOPE,
            cls.MANUAL_BINNING_REVIEWED_WITH_WARNINGS,
            cls.CANONICAL_MANIFEST_MISSING,
        }
