[mypy]
ignore_missing_imports = True
warn_unused_ignores = False
warn_return_any = False
disallow_any_unimported = False
disallow_subclassing_any = False
check_untyped_defs = False

[mypy-cardre.nodes.*]
ignore_errors = True

[mypy-cardre.modeling.adapters]
ignore_errors = True

[mypy-cardre.application.execution.*]
ignore_errors = True

[mypy-cardre.execution.step_runner]
ignore_errors = True

[mypy-cardre.api.routes.*]
ignore_errors = True
