"""Schema version constants for evidence kinds."""

SCHEMA_MODELLING_METADATA = "cardre.modelling_metadata.v1"
SCHEMA_SAMPLE_DEFINITION = "cardre.sample_definition.v1"
SCHEMA_REJECT_POPULATION_CONFIG = "cardre.reject_population_config.v1"
SCHEMA_REJECT_INFERENCE_RESULT = "cardre.reject_inference_result.v1"
SCHEMA_SELECTION_DEFINITION = "cardre.selection_definition.v1"
SCHEMA_WOE_TABLE = "cardre.woe_table.v1"
SCHEMA_WOE_IV_EVIDENCE = "cardre.woe_iv_evidence.v1"
SCHEMA_VARIABLE_CLUSTERING_EVIDENCE = "cardre.variable_clustering_evidence.v1"
SCHEMA_MODEL_ARTIFACT = "cardre.model_artifact.v1"
SCHEMA_SCORE_SCALING = "cardre.score_scaling.v1"
SCHEMA_VALIDATION_METRICS = "cardre.validation_metrics.v1"
SCHEMA_CUTOFF_ANALYSIS = "cardre.cutoff_analysis.v1"
SCHEMA_MANUAL_BINNING_OVERRIDES = "cardre.manual_binning_overrides.v1"
SCHEMA_FROZEN_SCORECARD_BUNDLE = "cardre.frozen_scorecard_bundle.v1"
SCHEMA_WOE_APPLICATION_EVIDENCE = "cardre.woe_application_evidence.v1"
SCHEMA_SCORE_APPLICATION_EVIDENCE = "cardre.score_application_evidence.v1"
SCHEMA_VALIDATION_EVIDENCE = "cardre.validation_evidence.v1"
