"""V1 compatibility shim — re-exports from cardre._evidence.

Phase 5: existing node code imports ``ArtifactEvidenceReader``,
``EvidenceKind``, and ``SCHEMA_*`` constants from ``cardre.evidence``.
These now live in ``cardre._evidence.*`` subpackage.

This shim re-exports everything so node code continues to work.
"""

from cardre._evidence.kinds import (
    AmbiguousEvidenceError,
    EvidenceError,
    EvidenceKind,
    EvidenceNotFoundError,
    EvidenceParseError,
    EvidenceSchemaError,
    LegacyEvidenceCompatibilityError,
)
from cardre._evidence.models import (
    ApplyModelEvidence,
    ApplyWoeEvidence,
    ArtifactEvidenceSummary,
    BinDefinition,
    BinVariable,
    CutoffAnalysis,
    FeatureSelectionEvidence,
    IvTable,
    ModellingMetadata,
    ModelArtifact,
    ProfileSummary,
    SampleDefinition,
    ScoreScaling,
    ScoredDataset,
    SelectionDefinition,
    SplitSummary,
    ValidationMetrics,
    VariableClusteringEvidence,
    WoeIvEvidence,
    WoeTable,
    WoeTransformEvidence,
)
from cardre._evidence.reader import ArtifactEvidenceReader
from cardre._evidence.schemas import (
    SCHEMA_APPLY_MODEL_EVIDENCE,
    SCHEMA_APPLY_WOE_EVIDENCE,
    SCHEMA_CALIBRATION_REPORT,
    SCHEMA_CUTOFF_ANALYSIS,
    SCHEMA_EXCLUSION_SUMMARY,
    SCHEMA_EXPLAINABILITY_REPORT,
    SCHEMA_FAIRNESS_REPORT,
    SCHEMA_FEATURE_SELECTION_EVIDENCE,
    SCHEMA_FROZEN_SCORECARD_BUNDLE,
    SCHEMA_HYPERPARAMETER_TUNING_EVIDENCE,
    SCHEMA_MANUAL_BINNING_OVERRIDES,
    SCHEMA_MODELLING_METADATA,
    SCHEMA_MODEL_ARTIFACT,
    SCHEMA_PROFILE_SUMMARY,
    SCHEMA_PROXY_RISK_REPORT,
    SCHEMA_REJECT_INFERENCE_RESULT,
    SCHEMA_REJECT_POPULATION_CONFIG,
    SCHEMA_REPORT_BUNDLE,
    SCHEMA_RESAMPLING_EVIDENCE,
    SCHEMA_RUN_MANIFEST,
    SCHEMA_SAMPLE_DEFINITION,
    SCHEMA_SCORE_SCALING,
    SCHEMA_SCORE_APPLICATION_EVIDENCE,
    SCHEMA_SELECTION_DEFINITION,
    SCHEMA_SPLIT_SUMMARY,
    SCHEMA_TECHNICAL_MANIFEST_INDEX,
    SCHEMA_VALIDATION_EVIDENCE,
    SCHEMA_VALIDATION_METRICS,
    SCHEMA_VARIABLE_CLUSTERING_EVIDENCE,
    SCHEMA_WOE_APPLICATION_EVIDENCE,
    SCHEMA_WOE_IV_EVIDENCE,
    SCHEMA_WOE_TABLE,
    SCHEMA_WOE_TRANSFORM_EVIDENCE,
)
# SCHEMA_BIN_DEFINITION lives in cardre.engine.binning.definition
from cardre._evidence.schemas import (
    SCHEMA_COMPARISON_ARTIFACT,
    SCHEMA_ENSEMBLE_MODEL_ARTIFACT,
)
from cardre.engine.binning.definition import SCHEMA_BIN_DEFINITION

__all__ = [
    "AmbiguousEvidenceError",
    "ApplyModelEvidence",
    "ApplyWoeEvidence",
    "ArtifactEvidenceReader",
    "ArtifactEvidenceSummary",
    "BinDefinition",
    "BinVariable",
    "CutoffAnalysis",
    "EvidenceError",
    "EvidenceKind",
    "EvidenceNotFoundError",
    "EvidenceParseError",
    "EvidenceSchemaError",
    "FeatureSelectionEvidence",
    "IvTable",
    "LegacyEvidenceCompatibilityError",
    "ModellingMetadata",
    "ModelArtifact",
    "ProfileSummary",
    "SCHEMA_APPLY_MODEL_EVIDENCE",
    "SCHEMA_APPLY_WOE_EVIDENCE",
    "SCHEMA_BIN_DEFINITION",
    "SCHEMA_CALIBRATION_REPORT",
    "SCHEMA_COMPARISON_ARTIFACT",
    "SCHEMA_CUTOFF_ANALYSIS",
    "SCHEMA_ENSEMBLE_MODEL_ARTIFACT",
    "SCHEMA_EXCLUSION_SUMMARY",
    "SCHEMA_EXPLAINABILITY_REPORT",
    "SCHEMA_FAIRNESS_REPORT",
    "SCHEMA_FEATURE_SELECTION_EVIDENCE",
    "SCHEMA_FROZEN_SCORECARD_BUNDLE",
    "SCHEMA_HYPERPARAMETER_TUNING_EVIDENCE",
    "SCHEMA_MANUAL_BINNING_OVERRIDES",
    "SCHEMA_MODELLING_METADATA",
    "SCHEMA_MODEL_ARTIFACT",
    "SCHEMA_PROFILE_SUMMARY",
    "SCHEMA_PROXY_RISK_REPORT",
    "SCHEMA_REJECT_INFERENCE_RESULT",
    "SCHEMA_REJECT_POPULATION_CONFIG",
    "SCHEMA_REPORT_BUNDLE",
    "SCHEMA_RESAMPLING_EVIDENCE",
    "SCHEMA_RUN_MANIFEST",
    "SCHEMA_SAMPLE_DEFINITION",
    "SCHEMA_SCORE_APPLICATION_EVIDENCE",
    "SCHEMA_SCORE_SCALING",
    "SCHEMA_SELECTION_DEFINITION",
    "SCHEMA_SPLIT_SUMMARY",
    "SCHEMA_TECHNICAL_MANIFEST_INDEX",
    "SCHEMA_VALIDATION_EVIDENCE",
    "SCHEMA_VALIDATION_METRICS",
    "SCHEMA_VARIABLE_CLUSTERING_EVIDENCE",
    "SCHEMA_WOE_APPLICATION_EVIDENCE",
    "SCHEMA_WOE_IV_EVIDENCE",
    "SCHEMA_WOE_TABLE",
    "SCHEMA_WOE_TRANSFORM_EVIDENCE",
    "SampleDefinition",
    "ScoreScaling",
    "ScoredDataset",
    "SelectionDefinition",
    "SplitSummary",
    "ValidationMetrics",
    "VariableClusteringEvidence",
    "WoeIvEvidence",
    "WoeTable",
    "WoeTransformEvidence",
]
