"""Typed Artifact Evidence Module — backward-compatible re-exports.

Provides typed access to Artifact contents so callers (Node types, reporting,
comparison, Plan service) ask for evidence by meaning rather than by inspecting
file bytes, JSON keys, and column names.

The implementation has been split into submodules under ``cardre/_evidence/``.
This module re-exports the public API for backward compatibility.
"""

from cardre._evidence.schemas import (
    SCHEMA_APPLY_MODEL_EVIDENCE,
    SCHEMA_APPLY_WOE_EVIDENCE,
    SCHEMA_CALIBRATION_REPORT,
    SCHEMA_COMPARISON_ARTIFACT,
    SCHEMA_CUTOFF_ANALYSIS,
    SCHEMA_ENSEMBLE_MODEL_ARTIFACT,
    SCHEMA_EXCLUSION_SUMMARY,
    SCHEMA_EXPLAINABILITY_REPORT,
    SCHEMA_FAIRNESS_REPORT,
    SCHEMA_FEATURE_SELECTION_EVIDENCE,
    SCHEMA_FROZEN_SCORECARD_BUNDLE,
    SCHEMA_HYPERPARAMETER_TUNING_EVIDENCE,
    SCHEMA_MANUAL_BINNING_OVERRIDES,
    SCHEMA_MODELLING_METADATA,
    SCHEMA_MODEL_ARTIFACT,
    SCHEMA_PROFILE_SUMMARY,
    SCHEMA_PROXY_RISK_REPORT,
    SCHEMA_REPORT_BUNDLE,
    SCHEMA_RESAMPLING_EVIDENCE,
    SCHEMA_RUN_MANIFEST,
    SCHEMA_REJECT_INFERENCE_RESULT,
    SCHEMA_REJECT_POPULATION_CONFIG,
    SCHEMA_SAMPLE_DEFINITION,
    SCHEMA_SCORE_APPLICATION_EVIDENCE,
    SCHEMA_SCORE_SCALING,
    SCHEMA_SELECTION_DEFINITION,
    SCHEMA_SPLIT_SUMMARY,
    SCHEMA_TECHNICAL_MANIFEST_INDEX,
    SCHEMA_VALIDATION_EVIDENCE,
    SCHEMA_VALIDATION_METRICS,
    SCHEMA_VARIABLE_CLUSTERING_EVIDENCE,
    SCHEMA_WOE_APPLICATION_EVIDENCE,
    SCHEMA_WOE_IV_EVIDENCE,
    SCHEMA_WOE_TRANSFORM_EVIDENCE,
    SCHEMA_WOE_TABLE,
)
from cardre.engine.binning.definition import SCHEMA_BIN_DEFINITION  # noqa: F401
from cardre._evidence.kinds import (
    EvidenceKind,
    EvidenceError,
    EvidenceSchemaError,
    LegacyEvidenceCompatibilityError,
    EvidenceNotFoundError,
    AmbiguousEvidenceError,
    EvidenceParseError,
)
from cardre._evidence.models import (
    ApplyModelEvidence,
    ApplyWoeEvidence,
    ArtifactEvidenceSummary,
    BinVariable,
    BinDefinition,
    ComparisonArtifact,
    Coefficient,
    ExclusionSummary,
    ExplainabilityReport,
    FairnessReport,
    FeatureSelectionEvidence,
    SelectedVariable,
    HyperparameterTuningEvidence,
    SelectionDefinition,
    ModellingMetadata,
    SampleDefinition,
    ProfileSummary,
    ProxyRiskReport,
    ReportBundleEvidence,
    ResamplingEvidence,
    RunManifestEvidence,
    WoeIvEvidence,
    ModelArtifact,
    ScoreScaling,
    ValidationMetrics,
    CutoffAnalysis,
    WoeTable,
    IvTable,
    ScoredDataset,
    SplitSummary,
    TechnicalManifestIndex,
    WoeTransformEvidence,
)
from cardre._evidence.reader import ArtifactEvidenceReader
from cardre._evidence.profiles import EVIDENCE_PROFILES as _EVIDENCE_PROFILES  # noqa: F401 — imported by tests/test_evidence.py

__all__ = [
    "SCHEMA_MODELLING_METADATA",
    "SCHEMA_SAMPLE_DEFINITION",
    "SCHEMA_SPLIT_SUMMARY",
    "SCHEMA_PROFILE_SUMMARY",
    "SCHEMA_EXCLUSION_SUMMARY",
    "SCHEMA_REJECT_POPULATION_CONFIG",
    "SCHEMA_REJECT_INFERENCE_RESULT",
    "SCHEMA_SELECTION_DEFINITION",
    "SCHEMA_WOE_TRANSFORM_EVIDENCE",
    "SCHEMA_WOE_TABLE",
    "SCHEMA_WOE_IV_EVIDENCE",
    "SCHEMA_VARIABLE_CLUSTERING_EVIDENCE",
    "SCHEMA_MODEL_ARTIFACT",
    "SCHEMA_ENSEMBLE_MODEL_ARTIFACT",
    "SCHEMA_SCORE_SCALING",
    "SCHEMA_VALIDATION_METRICS",
    "SCHEMA_CUTOFF_ANALYSIS",
    "SCHEMA_CALIBRATION_REPORT",
    "SCHEMA_MANUAL_BINNING_OVERRIDES",
    "SCHEMA_FROZEN_SCORECARD_BUNDLE",
    "SCHEMA_APPLY_WOE_EVIDENCE",
    "SCHEMA_WOE_APPLICATION_EVIDENCE",
    "SCHEMA_APPLY_MODEL_EVIDENCE",
    "SCHEMA_SCORE_APPLICATION_EVIDENCE",
    "SCHEMA_VALIDATION_EVIDENCE",
    "SCHEMA_REPORT_BUNDLE",
    "SCHEMA_RUN_MANIFEST",
    "SCHEMA_TECHNICAL_MANIFEST_INDEX",
    "SCHEMA_COMPARISON_ARTIFACT",
    "SCHEMA_FEATURE_SELECTION_EVIDENCE",
    "SCHEMA_RESAMPLING_EVIDENCE",
    "SCHEMA_HYPERPARAMETER_TUNING_EVIDENCE",
    "SCHEMA_EXPLAINABILITY_REPORT",
    "SCHEMA_FAIRNESS_REPORT",
    "SCHEMA_PROXY_RISK_REPORT",
    "EvidenceKind",
    "EvidenceError",
    "EvidenceSchemaError",
    "LegacyEvidenceCompatibilityError",
    "EvidenceNotFoundError",
    "AmbiguousEvidenceError",
    "EvidenceParseError",
    "BinVariable",
    "BinDefinition",
    "SplitSummary",
    "ProfileSummary",
    "ExclusionSummary",
    "WoeTransformEvidence",
    "ApplyWoeEvidence",
    "ApplyModelEvidence",
    "Coefficient",
    "SelectedVariable",
    "SelectionDefinition",
    "ModellingMetadata",
    "SampleDefinition",
    "WoeIvEvidence",
    "ModelArtifact",
    "ScoreScaling",
    "ValidationMetrics",
    "CutoffAnalysis",
    "WoeTable",
    "IvTable",
    "ScoredDataset",
    "ArtifactEvidenceReader",
    "ArtifactEvidenceSummary",
    "ReportBundleEvidence",
    "RunManifestEvidence",
    "TechnicalManifestIndex",
    "ComparisonArtifact",
    "FeatureSelectionEvidence",
    "ResamplingEvidence",
    "HyperparameterTuningEvidence",
    "ExplainabilityReport",
    "FairnessReport",
    "ProxyRiskReport",
]
