"""Test that errorCodes.ts mirrors cardre/domain/errors.py.

The TypeScript file is generated by ``scripts/generate-error-codes.py`` from
the Python ``ErrorCode`` enum. These tests assert the generated file is
current in both directions, so drift is caught in CI. Transport codes are
client-only and hand-maintained; they are excluded below.
"""

from __future__ import annotations

import re
from pathlib import Path

from cardre.domain.errors import INTERNAL_ERROR_CODES, ErrorCode


def _parse_ts_server_codes() -> set[str]:
    """Extract server-side error code strings from errorCodes.ts.

    Transport-only codes (SIDECAR_UNREACHABLE, REQUEST_TIMEOUT, etc.)
    are excluded — they are client-side only and have no Python counterpart.
    """
    ts_path = Path(__file__).parents[1] / "frontend" / "src" / "api" / "errorCodes.ts"
    text = ts_path.read_text()
    transport_codes = {
        "SIDECAR_UNREACHABLE",
        "REQUEST_TIMEOUT",
        "REQUEST_ABORTED",
        "EMPTY_OK_BODY",
        "EMPTY_ERROR_RESPONSE",
        "MALFORMED_JSON_RESPONSE",
        "HTML_ERROR_RESPONSE",
        "NON_JSON_ERROR_RESPONSE",
    }
    codes: set[str] = set()
    for m in re.finditer(r'(\w+):\s*"(\w+)"', text):
        name, value = m.group(1), m.group(2)
        if name not in transport_codes and name != "ErrorCodes":
            codes.add(value)
    return codes


class TestErrorCodeSync:
    def _python_codes(self) -> set[str]:
        """Server-side Python codes (internal codes excluded)."""
        return {e.value for e in ErrorCode} - {e.value for e in INTERNAL_ERROR_CODES}

    def test_ts_server_codes_match_python(self):
        """errorCodes.ts server codes must equal the Python ErrorCode set."""
        ts_codes = _parse_ts_server_codes()
        py_codes = self._python_codes()
        assert ts_codes == py_codes, (
            f"errorCodes.ts and cardre/domain/errors.py have diverged.\n"
            f"errorCodes.ts has codes not in Python: {sorted(ts_codes - py_codes)}\n"
            f"Python has codes not in errorCodes.ts: {sorted(py_codes - ts_codes)}"
        )

    def test_internal_codes_excluded_from_ts(self):
        """Internal-only ErrorCode members must not appear in errorCodes.ts."""
        ts_codes = _parse_ts_server_codes()
        leaked = {e.value for e in INTERNAL_ERROR_CODES} & ts_codes
        assert not leaked, (
            f"Internal-only ErrorCode members leaked into errorCodes.ts: "
            f"{sorted(leaked)}. They are excluded by the generator."
        )
