from __future__ import annotations

from cardre._evidence.kinds import EvidenceKind
from cardre._evidence.profiles import EVIDENCE_PROFILES
from cardre._evidence.schemas import (
    SCHEMA_APPLY_MODEL_EVIDENCE,
    SCHEMA_APPLY_WOE_EVIDENCE,
    SCHEMA_COMPARISON_ARTIFACT,
    SCHEMA_EXCLUSION_SUMMARY,
    SCHEMA_EXPLAINABILITY_REPORT,
    SCHEMA_FAIRNESS_REPORT,
    SCHEMA_FEATURE_SELECTION_EVIDENCE,
    SCHEMA_HYPERPARAMETER_TUNING_EVIDENCE,
    SCHEMA_PROFILE_SUMMARY,
    SCHEMA_PROXY_RISK_REPORT,
    SCHEMA_REPORT_BUNDLE,
    SCHEMA_RESAMPLING_EVIDENCE,
    SCHEMA_RUN_MANIFEST,
    SCHEMA_SPLIT_SUMMARY,
    SCHEMA_TECHNICAL_MANIFEST_INDEX,
    SCHEMA_WOE_TRANSFORM_EVIDENCE,
)


def test_launch_critical_profiles_exist_and_match_schema_versions() -> None:
    expected = {
        EvidenceKind.SPLIT_SUMMARY: SCHEMA_SPLIT_SUMMARY,
        EvidenceKind.PROFILE_SUMMARY: SCHEMA_PROFILE_SUMMARY,
        EvidenceKind.EXCLUSION_SUMMARY: SCHEMA_EXCLUSION_SUMMARY,
        EvidenceKind.WOE_TRANSFORM_EVIDENCE: SCHEMA_WOE_TRANSFORM_EVIDENCE,
        EvidenceKind.APPLY_WOE_EVIDENCE: SCHEMA_APPLY_WOE_EVIDENCE,
        EvidenceKind.APPLY_MODEL_EVIDENCE: SCHEMA_APPLY_MODEL_EVIDENCE,
        EvidenceKind.REPORT_BUNDLE: SCHEMA_REPORT_BUNDLE,
        EvidenceKind.RUN_MANIFEST: SCHEMA_RUN_MANIFEST,
        EvidenceKind.TECHNICAL_MANIFEST_INDEX: SCHEMA_TECHNICAL_MANIFEST_INDEX,
        EvidenceKind.COMPARISON_ARTIFACT: SCHEMA_COMPARISON_ARTIFACT,
        EvidenceKind.FEATURE_SELECTION_EVIDENCE: SCHEMA_FEATURE_SELECTION_EVIDENCE,
        EvidenceKind.RESAMPLING_EVIDENCE: SCHEMA_RESAMPLING_EVIDENCE,
        EvidenceKind.HYPERPARAMETER_TUNING_EVIDENCE: SCHEMA_HYPERPARAMETER_TUNING_EVIDENCE,
        EvidenceKind.ENSEMBLE_MODEL_ARTIFACT: "cardre.ensemble_model_artifact.v1",
        EvidenceKind.EXPLAINABILITY_REPORT: SCHEMA_EXPLAINABILITY_REPORT,
        EvidenceKind.FAIRNESS_REPORT: SCHEMA_FAIRNESS_REPORT,
        EvidenceKind.PROXY_RISK_REPORT: SCHEMA_PROXY_RISK_REPORT,
    }

    for kind, schema_version in expected.items():
        assert kind in EVIDENCE_PROFILES
        assert EVIDENCE_PROFILES[kind].schema_version == schema_version


def test_backwards_compatible_enum_aliases_point_to_new_kinds() -> None:
    assert EvidenceKind.WOE_APPLICATION_EVIDENCE is EvidenceKind.APPLY_WOE_EVIDENCE
    assert EvidenceKind.SCORE_APPLICATION_EVIDENCE is EvidenceKind.APPLY_MODEL_EVIDENCE
