/**
 * Hand-written second source for error codes.
 *
 * The canonical set lives in `cardre/api/errors.py` (Python). This file
 * mirrors it manually and must be kept in sync by hand until a generator
 * is added. The set is small (~21 codes) and changes infrequently, so the
 * duplication is accepted.
 *
 * A CI test (`tests/test_error_code_sync.py`) asserts that the server-code
 * subset of this file is a subset of the Python canonical set, so drift
 * will be caught.
 */
export const ErrorCodes = {
  SIDECAR_UNREACHABLE: "SIDECAR_UNREACHABLE",
  REQUEST_TIMEOUT: "REQUEST_TIMEOUT",
  REQUEST_ABORTED: "REQUEST_ABORTED",
  EMPTY_OK_BODY: "EMPTY_OK_BODY",
  EMPTY_ERROR_RESPONSE: "EMPTY_ERROR_RESPONSE",
  MALFORMED_JSON_RESPONSE: "MALFORMED_JSON_RESPONSE",
  HTML_ERROR_RESPONSE: "HTML_ERROR_RESPONSE",
  NON_JSON_ERROR_RESPONSE: "NON_JSON_ERROR_RESPONSE",
  GOVERNANCE_DISABLED: "GOVERNANCE_DISABLED",
  PLAN_VERSION_IMMUTABLE: "PLAN_VERSION_IMMUTABLE",
  STORE_VERSION_INCOMPATIBLE: "STORE_VERSION_INCOMPATIBLE",
  RUN_EXECUTION_FAILED: "RUN_EXECUTION_FAILED",
  PROJECT_NOT_FOUND: "PROJECT_NOT_FOUND",
  PLAN_NOT_FOUND: "PLAN_NOT_FOUND",
  PLAN_VERSION_NOT_FOUND: "PLAN_VERSION_NOT_FOUND",
  RUN_NOT_FOUND: "RUN_NOT_FOUND",
  ARTIFACT_NOT_FOUND: "ARTIFACT_NOT_FOUND",
  STEP_NOT_FOUND: "STEP_NOT_FOUND",
  BRANCH_NOT_FOUND: "BRANCH_NOT_FOUND",
  COMPARISON_NOT_FOUND: "COMPARISON_NOT_FOUND",
  REVIEW_NOT_FOUND: "REVIEW_NOT_FOUND",
  MISSING_PROJECT_ID: "MISSING_PROJECT_ID",
  MISSING_PROJECT_PATH: "MISSING_PROJECT_PATH",
  RAW_PROJECT_PATH_DISABLED: "RAW_PROJECT_PATH_DISABLED",
  CONCURRENT_RUN: "CONCURRENT_RUN",
  STORE_ALREADY_EXISTS: "STORE_ALREADY_EXISTS",
  INVALID_PROJECT_PATH: "INVALID_PROJECT_PATH",
  MISSING_PARAMETER: "MISSING_PARAMETER",
  PLAN_VERSION_NOT_COMMITTED: "PLAN_VERSION_NOT_COMMITTED",
} as const;
