/**
 * Auto-generated from cardre/domain/errors.py by
 * scripts/generate-error-codes.py — do not edit server codes by hand;
 * transport codes below are client-only.
 */

export const ErrorCodes = {
  SIDECAR_UNREACHABLE: "SIDECAR_UNREACHABLE",
  REQUEST_TIMEOUT: "REQUEST_TIMEOUT",
  REQUEST_ABORTED: "REQUEST_ABORTED",
  EMPTY_OK_BODY: "EMPTY_OK_BODY",
  EMPTY_ERROR_RESPONSE: "EMPTY_ERROR_RESPONSE",
  MALFORMED_JSON_RESPONSE: "MALFORMED_JSON_RESPONSE",
  HTML_ERROR_RESPONSE: "HTML_ERROR_RESPONSE",
  NON_JSON_ERROR_RESPONSE: "NON_JSON_ERROR_RESPONSE",
  BAD_REQUEST: "BAD_REQUEST",
  PLAN_VERSION_IMMUTABLE: "PLAN_VERSION_IMMUTABLE",
  STORE_VERSION_INCOMPATIBLE: "STORE_VERSION_INCOMPATIBLE",
  PROJECT_NOT_FOUND: "PROJECT_NOT_FOUND",
  PLAN_NOT_FOUND: "PLAN_NOT_FOUND",
  PLAN_VERSION_NOT_FOUND: "PLAN_VERSION_NOT_FOUND",
  RUN_NOT_FOUND: "RUN_NOT_FOUND",
  ARTIFACT_NOT_FOUND: "ARTIFACT_NOT_FOUND",
  STEP_NOT_FOUND: "STEP_NOT_FOUND",
  REVIEW_NOT_FOUND: "REVIEW_NOT_FOUND",
  MISSING_PROJECT_ID: "MISSING_PROJECT_ID",
  MISSING_PROJECT_PATH: "MISSING_PROJECT_PATH",
  CONCURRENT_RUN: "CONCURRENT_RUN",
  STORE_ALREADY_EXISTS: "STORE_ALREADY_EXISTS",
  INVALID_PROJECT_PATH: "INVALID_PROJECT_PATH",
  MISSING_PARAMETER: "MISSING_PARAMETER",
  PLAN_VERSION_NOT_COMMITTED: "PLAN_VERSION_NOT_COMMITTED",
  GRAPH_VALIDATION_ERROR: "GRAPH_VALIDATION_ERROR",
  RUN_NOT_RUNNING: "RUN_NOT_RUNNING",
  RUN_PLAN_VERSION_MISMATCH: "RUN_PLAN_VERSION_MISMATCH",
  MISSING_INPUT_ARTIFACT: "MISSING_INPUT_ARTIFACT",
  PARAMETER_VALIDATION_ERROR: "PARAMETER_VALIDATION_ERROR",
  ARTIFACT_READ_ERROR: "ARTIFACT_READ_ERROR",
  ARTIFACT_WRITE_ERROR: "ARTIFACT_WRITE_ERROR",
  NODE_VERSION_MISMATCH: "NODE_VERSION_MISMATCH",
  RUN_SCOPE_NOT_AVAILABLE_FOR_LAUNCH: "RUN_SCOPE_NOT_AVAILABLE_FOR_LAUNCH",
  OPTIONAL_DEPENDENCY_NOT_INSTALLED: "OPTIONAL_DEPENDENCY_NOT_INSTALLED",
  PLAN_VERSION_ALREADY_COMMITTED: "PLAN_VERSION_ALREADY_COMMITTED",
  STALE_SNAPSHOT: "STALE_SNAPSHOT",
  EVIDENCE_VALIDATION_ERROR: "EVIDENCE_VALIDATION_ERROR",
  STALE_HEAD_VERSION: "STALE_HEAD_VERSION",
  STALE_BASE_VERSION: "STALE_BASE_VERSION",
  REPORT_BLOCKED: "REPORT_BLOCKED",
  CANONICAL_MANIFEST_MISSING: "CANONICAL_MANIFEST_MISSING",
  EXPORT_RUN_NOT_FOUND: "EXPORT_RUN_NOT_FOUND",
  REGISTRY_CORRUPTED: "REGISTRY_CORRUPTED",
  RUN_SCOPE_INVALID: "RUN_SCOPE_INVALID",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

const VALID_CODES: ReadonlySet<string> = new Set(Object.values(ErrorCodes));

export function isErrorCode(value: unknown): value is ErrorCode {
  return typeof value === "string" && VALID_CODES.has(value);
}
