/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Return API health status.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Projects
         * @description List all registered projects from the registry.
         */
        get: operations["list_projects_projects_get"];
        put?: never;
        /**
         * Create Project
         * @description Create a new project by bootstrapping a fresh store at body.path.
         */
        post: operations["create_project_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Project
         * @description Get a single project by ID, resolved via the registry.
         */
        get: operations["get_project_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Plans */
        get: operations["list_plans_projects__project_id__plans_get"];
        put?: never;
        /** Create Plan */
        post: operations["create_plan_projects__project_id__plans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/plans/{plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Plan */
        get: operations["get_plan_projects__project_id__plans__plan_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/plans/{plan_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Plan Versions */
        get: operations["list_plan_versions_projects__project_id__plans__plan_id__versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/plan-versions/{version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Plan Version */
        get: operations["get_plan_version_projects__project_id__plan_versions__version_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Plan Version */
        patch: operations["update_plan_version_projects__project_id__plan_versions__version_id__patch"];
        trace?: never;
    };
    "/projects/{project_id}/plan-versions/{version_id}/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Commit Plan Version */
        post: operations["commit_plan_version_projects__project_id__plan_versions__version_id__commit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/plan-versions/{version_id}/steps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Plan Version Steps */
        get: operations["get_plan_version_steps_projects__project_id__plan_versions__version_id__steps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_projects__project_id__runs_get"];
        put?: never;
        /** Create Run */
        post: operations["create_run_projects__project_id__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_projects__project_id__runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/runs/{run_id}/steps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Steps */
        get: operations["get_run_steps_projects__project_id__runs__run_id__steps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/runs/{run_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Evidence */
        get: operations["get_run_evidence_projects__project_id__runs__run_id__evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Run */
        post: operations["cancel_run_projects__project_id__runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/steps/{step_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Step Evidence Staleness */
        get: operations["get_step_evidence_staleness_projects__project_id__steps__step_id__evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/artifacts/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artifact */
        get: operations["get_artifact_projects__project_id__artifacts__artifact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/node-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Node Types */
        get: operations["list_node_types_node_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/exports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Exports */
        get: operations["list_exports_projects__project_id__exports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Reports */
        get: operations["list_reports_projects__project_id__reports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/runs/{run_id}/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Run Reports */
        get: operations["list_run_reports_projects__project_id__runs__run_id__reports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/governance/branches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Branches */
        get: operations["list_branches_projects__project_id__governance_branches_get"];
        put?: never;
        /** Create Branch */
        post: operations["create_branch_projects__project_id__governance_branches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/governance/branches/{branch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Branch */
        get: operations["get_branch_projects__project_id__governance_branches__branch_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/governance/comparisons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Comparisons */
        get: operations["list_comparisons_projects__project_id__governance_comparisons_get"];
        put?: never;
        /** Create Comparison */
        post: operations["create_comparison_projects__project_id__governance_comparisons_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/governance/comparisons/{comparison_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Comparison */
        get: operations["get_comparison_projects__project_id__governance_comparisons__comparison_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/governance/comparisons/{comparison_id}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Comparison */
        post: operations["refresh_comparison_projects__project_id__governance_comparisons__comparison_id__refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/governance/champion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Champion */
        get: operations["get_champion_projects__project_id__governance_champion_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/governance/champion/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assign Champion */
        post: operations["assign_champion_projects__project_id__governance_champion_assign_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/governance/manual-binning-reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Manual Binning Reviews */
        get: operations["list_manual_binning_reviews_projects__project_id__governance_manual_binning_reviews_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/governance/manual-binning-reviews/{review_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Manual Binning Review */
        get: operations["get_manual_binning_review_projects__project_id__governance_manual_binning_reviews__review_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Manual Binning Review */
        patch: operations["update_manual_binning_review_projects__project_id__governance_manual_binning_reviews__review_id__patch"];
        trace?: never;
    };
    "/projects/{project_id}/governance/manual-binning-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Manual Binning */
        post: operations["preview_manual_binning_projects__project_id__governance_manual_binning_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/governance/apply-manual-binning-edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply Manual Binning Edit */
        post: operations["apply_manual_binning_edit_projects__project_id__governance_apply_manual_binning_edit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArtifactResponse */
        ArtifactResponse: {
            /** Artifact Id */
            artifact_id: string;
            /** Artifact Type */
            artifact_type: string;
            /** Role */
            role: string;
            /** Path */
            path: string;
            /** Physical Hash */
            physical_hash: string;
            /** Logical Hash */
            logical_hash: string;
            /** Media Type */
            media_type: string;
            /** Created At */
            created_at: string;
        };
        /** BranchCreateRequest */
        BranchCreateRequest: {
            /** Plan Id */
            plan_id: string;
            /** Name */
            name: string;
            /**
             * Branch Type
             * @default challenger
             */
            branch_type: string;
            /** Base Plan Version Id */
            base_plan_version_id: string;
            /** Head Plan Version Id */
            head_plan_version_id: string;
            /** Description */
            description?: string | null;
            /** Base Branch Id */
            base_branch_id?: string | null;
            /** Branch Point Step Id */
            branch_point_step_id?: string | null;
            /**
             * Created Reason
             * @default
             */
            created_reason: string;
        };
        /** BranchListResponse */
        BranchListResponse: {
            /** Branches */
            branches: components["schemas"]["BranchResponse"][];
        };
        /** BranchResponse */
        BranchResponse: {
            /** Branch Id */
            branch_id: string;
            /** Project Id */
            project_id: string;
            /** Plan Id */
            plan_id: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Branch Type */
            branch_type: string;
            /**
             * Status
             * @default active
             */
            status: string;
            /** Base Branch Id */
            base_branch_id?: string | null;
            /** Base Plan Version Id */
            base_plan_version_id: string;
            /** Head Plan Version Id */
            head_plan_version_id: string;
            /** Branch Point Step Id */
            branch_point_step_id?: string | null;
            /** Branch Point Canonical Step Id */
            branch_point_canonical_step_id?: string | null;
            /**
             * Created Reason
             * @default
             */
            created_reason: string;
            /**
             * Created At
             * @default
             */
            created_at: string;
            /**
             * Updated At
             * @default
             */
            updated_at: string;
        };
        /** ChampionAssignmentRequest */
        ChampionAssignmentRequest: {
            /** Plan Id */
            plan_id: string;
            /** Branch Id */
            branch_id: string;
            /** Comparison Id */
            comparison_id: string;
            /** Comparison Snapshot Id */
            comparison_snapshot_id: string;
            /**
             * Assigned Reason
             * @default
             */
            assigned_reason: string;
        };
        /** ChampionAssignmentResponse */
        ChampionAssignmentResponse: {
            /** Champion Assignment Id */
            champion_assignment_id: string;
            /** Project Id */
            project_id: string;
            /** Plan Id */
            plan_id: string;
            /** Champion Branch Id */
            champion_branch_id: string;
            /** Selected Plan Version Id */
            selected_plan_version_id: string;
            /**
             * Assigned At
             * @default
             */
            assigned_at: string;
            /** Superseded At */
            superseded_at?: string | null;
        };
        /** ChampionResponse */
        ChampionResponse: {
            assignment?: components["schemas"]["ChampionAssignmentResponse"] | null;
        };
        /** ComparisonCreateRequest */
        ComparisonCreateRequest: {
            /** Plan Id */
            plan_id: string;
            /** Baseline Branch Id */
            baseline_branch_id: string;
            /**
             * Challenger Branch Ids
             * @default []
             */
            challenger_branch_ids: string[];
            /** Created Reason */
            created_reason?: string | null;
        };
        /** ComparisonListResponse */
        ComparisonListResponse: {
            /** Comparisons */
            comparisons: components["schemas"]["ComparisonResponse"][];
        };
        /** ComparisonResponse */
        ComparisonResponse: {
            /** Comparison Id */
            comparison_id: string;
            /** Project Id */
            project_id: string;
            /** Plan Id */
            plan_id: string;
            /** Baseline Branch Id */
            baseline_branch_id: string;
            /**
             * Created At
             * @default
             */
            created_at: string;
            /** Latest Ready */
            latest_ready?: boolean | null;
        };
        /** DiagnosticResponse */
        DiagnosticResponse: {
            /**
             * Code
             * @default UNKNOWN
             */
            code: string;
            /**
             * Message
             * @default
             */
            message: string;
            /**
             * Severity
             * @default error
             */
            severity: string;
            /** Source */
            source?: string | null;
            /** Context */
            context?: {
                [key: string]: unknown;
            };
            /** Created At */
            created_at?: string | null;
        };
        /** EvidenceArtifactResponse */
        EvidenceArtifactResponse: {
            /** Evidence Artifact Id */
            evidence_artifact_id: string;
            /** Evidence Edge Id */
            evidence_edge_id: string;
            /** Artifact Id */
            artifact_id: string;
            /** Role */
            role: string;
            /**
             * Created At
             * @default
             */
            created_at: string;
        };
        /** ExportListResponse */
        ExportListResponse: {
            /** Exports */
            exports: components["schemas"]["ExportResponse"][];
        };
        /** ExportResponse */
        ExportResponse: {
            /** Export Id */
            export_id: string;
            /** Run Id */
            run_id: string;
            /** Export Type */
            export_type: string;
            /** Path */
            path: string;
            /** Created At */
            created_at: string;
            /**
             * Size Bytes
             * @default 0
             */
            size_bytes: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             */
            status: string;
            /**
             * Version
             * @default 0.2.0
             */
            version: string;
            /**
             * Launch Node Count
             * @default 0
             */
            launch_node_count: number;
            /**
             * Deferred Node Count
             * @default 0
             */
            deferred_node_count: number;
            /**
             * Governance Enabled
             * @default false
             */
            governance_enabled: boolean;
        };
        /** ManualBinningEditRequest */
        ManualBinningEditRequest: {
            /** Plan Version Id */
            plan_version_id: string;
            /** Step Id */
            step_id: string;
            /** Overrides */
            overrides?: {
                [key: string]: unknown;
            }[];
            /**
             * Reviewer Notes
             * @default
             */
            reviewer_notes: string;
            /**
             * Status
             * @default pending
             */
            status: string;
            /** Affected Downstream Step Ids */
            affected_downstream_step_ids?: string[];
        };
        /** ManualBinningEditResponse */
        ManualBinningEditResponse: {
            /** New Plan Version Id */
            new_plan_version_id: string;
            /** Review Id */
            review_id: string;
            /** Affected Step Ids */
            affected_step_ids?: string[];
        };
        /** ManualBinningPreviewRequest */
        ManualBinningPreviewRequest: {
            /** Variable Data */
            variable_data: {
                [key: string]: unknown;
            };
        };
        /** ManualBinningPreviewResponse */
        ManualBinningPreviewResponse: {
            /** Woe By Bin */
            woe_by_bin: {
                [key: string]: unknown;
            }[];
            /** Iv */
            iv: number;
            /** Event Rate By Bin */
            event_rate_by_bin: {
                [key: string]: unknown;
            }[];
        };
        /** ManualBinningReviewResponse */
        ManualBinningReviewResponse: {
            /** Review Id */
            review_id: string;
            /** Plan Version Id */
            plan_version_id: string;
            /** Step Id */
            step_id: string;
            /** Status */
            status: string;
            /**
             * Reviewer Notes
             * @default
             */
            reviewer_notes: string;
            /** Affected Downstream Step Ids */
            affected_downstream_step_ids?: string[];
            /**
             * Created At
             * @default
             */
            created_at: string;
            /**
             * Updated At
             * @default
             */
            updated_at: string;
        };
        /** ManualBinningReviewUpdate */
        ManualBinningReviewUpdate: {
            /** Status */
            status?: string | null;
            /** Reviewer Notes */
            reviewer_notes?: string | null;
        };
        /** NodeTypeListResponse */
        NodeTypeListResponse: {
            /** Node Types */
            node_types: components["schemas"]["NodeTypeResponse"][];
        };
        /** NodeTypeResponse */
        NodeTypeResponse: {
            /** Node Type */
            node_type: string;
            /**
             * Display Name
             * @default
             */
            display_name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Category
             * @default
             */
            category: string;
            /**
             * Tier
             * @default launch
             */
            tier: string;
            /**
             * Has Params
             * @default false
             */
            has_params: boolean;
        };
        /** PlanCreateRequest */
        PlanCreateRequest: {
            /** Name */
            name: string;
        };
        /** PlanListResponse */
        PlanListResponse: {
            /** Plans */
            plans: components["schemas"]["PlanResponse"][];
        };
        /** PlanResponse */
        PlanResponse: {
            /** Plan Id */
            plan_id: string;
            /** Project Id */
            project_id: string;
            /** Name */
            name: string;
            /** Created At */
            created_at: string;
        };
        /** PlanStepResponse */
        PlanStepResponse: {
            /** Step Id */
            step_id: string;
            /** Plan Version Id */
            plan_version_id: string;
            /** Node Type */
            node_type: string;
            /** Node Version */
            node_version: string;
            /** Category */
            category: string;
            /** Params */
            params?: {
                [key: string]: unknown;
            };
            /**
             * Params Hash
             * @default
             */
            params_hash: string;
            /** Parent Step Ids */
            parent_step_ids?: string[];
            /**
             * Branch Label
             * @default
             */
            branch_label: string;
            /**
             * Position
             * @default 0
             */
            position: number;
            /**
             * Canonical Step Id
             * @default
             */
            canonical_step_id: string;
            /** Branch Id */
            branch_id?: string | null;
        };
        /** PlanVersionListResponse */
        PlanVersionListResponse: {
            /** Versions */
            versions: components["schemas"]["PlanVersionResponse"][];
        };
        /** PlanVersionResponse */
        PlanVersionResponse: {
            /** Plan Version Id */
            plan_version_id: string;
            /** Plan Id */
            plan_id: string;
            /** Version Number */
            version_number: number;
            /** Is Committed */
            is_committed: boolean;
            /** Created At */
            created_at: string;
            /**
             * Description
             * @default
             */
            description: string;
        };
        /** PlanVersionUpdate */
        PlanVersionUpdate: {
            /** Description */
            description?: string | null;
        };
        /** ProjectCreateRequest */
        ProjectCreateRequest: {
            /** Name */
            name: string;
            /** Path */
            path: string;
        };
        /** ProjectListResponse */
        ProjectListResponse: {
            /** Projects */
            projects: components["schemas"]["ProjectResponse"][];
            /** Unavailable Projects */
            unavailable_projects?: components["schemas"]["UnavailableProjectResponse"][];
        };
        /** ProjectResponse */
        ProjectResponse: {
            /** Project Id */
            project_id: string;
            /** Name */
            name: string;
            /** Created At */
            created_at: string;
            /** Cardre Version */
            cardre_version: string;
        };
        /** ReportListResponse */
        ReportListResponse: {
            /** Reports */
            reports: components["schemas"]["ReportResponse"][];
        };
        /** ReportResponse */
        ReportResponse: {
            /** Report Id */
            report_id: string;
            /** Run Id */
            run_id?: string | null;
            /** Report Type */
            report_type: string;
            /** Path */
            path: string;
            /** Created At */
            created_at: string;
        };
        /** RunCreateRequest */
        RunCreateRequest: {
            /** Plan Version Id */
            plan_version_id: string;
            /**
             * Force
             * @default false
             */
            force: boolean;
            /**
             * Sync
             * @default false
             */
            sync: boolean;
        };
        /**
         * RunEvidenceEdgeResponse
         * @description Typed response for a single evidence edge in a run (#216).
         *
         *     Includes full provenance fields from EvidenceEdgeResponse plus
         *     nested artifacts so the generated schema and frontend types match
         *     the actual payload shape.
         */
        RunEvidenceEdgeResponse: {
            /** Evidence Edge Id */
            evidence_edge_id: string;
            /** Run Id */
            run_id: string;
            /** Run Step Id */
            run_step_id: string;
            /** Plan Version Id */
            plan_version_id: string;
            /** Step Id */
            step_id: string;
            /** Parent Step Id */
            parent_step_id: string;
            /** Source Run Id */
            source_run_id: string;
            /** Source Run Step Id */
            source_run_step_id: string;
            /** Policy */
            policy: string;
            /** Source Label */
            source_label: string;
            /**
             * Is Reused
             * @default false
             */
            is_reused: boolean;
            /**
             * Is Stale
             * @default false
             */
            is_stale: boolean;
            /** Stale Reason */
            stale_reason?: string | null;
            /**
             * Created At
             * @default
             */
            created_at: string;
            /** Artifacts */
            artifacts?: components["schemas"]["EvidenceArtifactResponse"][];
        };
        /** RunListResponse */
        RunListResponse: {
            /** Runs */
            runs: components["schemas"]["RunResponse"][];
        };
        /** RunResponse */
        RunResponse: {
            /** Run Id */
            run_id: string;
            /** Plan Version Id */
            plan_version_id: string;
            /** Status */
            status: string;
            /** Started At */
            started_at: string;
            /** Finished At */
            finished_at?: string | null;
            /**
             * Step Count
             * @default 0
             */
            step_count: number;
            /** Branch Id */
            branch_id?: string | null;
            /** Executed Step Ids */
            executed_step_ids?: string[];
            /** Diagnostics */
            diagnostics?: components["schemas"]["DiagnosticResponse"][];
            latest_error?: components["schemas"]["DiagnosticResponse"] | null;
            /** Heartbeat At */
            heartbeat_at?: string | null;
            /**
             * Is Stale
             * @default false
             */
            is_stale: boolean;
        };
        /** RunStepResponse */
        RunStepResponse: {
            /** Run Step Id */
            run_step_id: string;
            /** Run Id */
            run_id: string;
            /** Step Id */
            step_id: string;
            /** Plan Version Id */
            plan_version_id: string;
            /** Status */
            status: string;
            /** Started At */
            started_at: string;
            /** Finished At */
            finished_at?: string | null;
            /** Execution Fingerprint */
            execution_fingerprint?: {
                [key: string]: unknown;
            };
            /** Warnings */
            warnings?: components["schemas"]["DiagnosticResponse"][];
            /** Errors */
            errors?: components["schemas"]["DiagnosticResponse"][];
        };
        /** StalenessExplanationResponse */
        StalenessExplanationResponse: {
            /** Step Id */
            step_id: string;
            /** Status */
            status: string;
            /** Upstream Changes */
            upstream_changes: {
                [key: string]: boolean;
            };
            /** Missing Evidence */
            missing_evidence?: string[];
        };
        /**
         * UnavailableProjectResponse
         * @description A registered project that could not be opened (corrupt, missing, etc).
         */
        UnavailableProjectResponse: {
            /** Project Id */
            project_id: string;
            /** Root */
            root: string;
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_projects_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectListResponse"];
                };
            };
        };
    };
    create_project_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_plans_projects__project_id__plans_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_plan_projects__project_id__plans_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_plan_projects__project_id__plans__plan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_plan_versions_projects__project_id__plans__plan_id__versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanVersionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_plan_version_projects__project_id__plan_versions__version_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanVersionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_plan_version_projects__project_id__plan_versions__version_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                version_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanVersionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanVersionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    commit_plan_version_projects__project_id__plan_versions__version_id__commit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanVersionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_plan_version_steps_projects__project_id__plan_versions__version_id__steps_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanStepResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_projects__project_id__runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_projects__project_id__runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_projects__project_id__runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_steps_projects__project_id__runs__run_id__steps_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStepResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_evidence_projects__project_id__runs__run_id__evidence_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunEvidenceEdgeResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_projects__project_id__runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_step_evidence_staleness_projects__project_id__steps__step_id__evidence_get: {
        parameters: {
            query: {
                plan_version_id: string;
                branch_id?: string | null;
            };
            header?: never;
            path: {
                project_id: string;
                step_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StalenessExplanationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_artifact_projects__project_id__artifacts__artifact_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_node_types_node_types_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeTypeListResponse"];
                };
            };
        };
    };
    list_exports_projects__project_id__exports_get: {
        parameters: {
            query?: {
                run_id?: string | null;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reports_projects__project_id__reports_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_run_reports_projects__project_id__runs__run_id__reports_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_branches_projects__project_id__governance_branches_get: {
        parameters: {
            query?: {
                plan_id?: string | null;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BranchListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_branch_projects__project_id__governance_branches_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BranchCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BranchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_branch_projects__project_id__governance_branches__branch_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                branch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BranchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_comparisons_projects__project_id__governance_comparisons_get: {
        parameters: {
            query?: {
                plan_id?: string | null;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparisonListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_comparison_projects__project_id__governance_comparisons_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComparisonCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparisonResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_comparison_projects__project_id__governance_comparisons__comparison_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                comparison_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparisonResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_comparison_projects__project_id__governance_comparisons__comparison_id__refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                comparison_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparisonResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_champion_projects__project_id__governance_champion_get: {
        parameters: {
            query: {
                plan_id: string;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChampionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_champion_projects__project_id__governance_champion_assign_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChampionAssignmentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChampionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_manual_binning_reviews_projects__project_id__governance_manual_binning_reviews_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManualBinningReviewResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_manual_binning_review_projects__project_id__governance_manual_binning_reviews__review_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                review_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManualBinningReviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_manual_binning_review_projects__project_id__governance_manual_binning_reviews__review_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                review_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualBinningReviewUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManualBinningReviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_manual_binning_projects__project_id__governance_manual_binning_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualBinningPreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManualBinningPreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_manual_binning_edit_projects__project_id__governance_apply_manual_binning_edit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualBinningEditRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManualBinningEditResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
