"""Schema version constants for evidence kinds.

Canonical source for the bin-definition schema constant is
cardre.domain.binning.definition.
"""

SCHEMA_MODELLING_METADATA = "cardre.modelling_metadata.v1"
SCHEMA_SAMPLE_DEFINITION = "cardre.sample_definition.v1"
SCHEMA_SPLIT_SUMMARY = "cardre.split_summary.v1"
SCHEMA_PROFILE_SUMMARY = "cardre.profile_summary.v1"
SCHEMA_EXCLUSION_SUMMARY = "cardre.exclusion_summary.v1"
SCHEMA_SELECTION_DEFINITION = "cardre.selection_definition.v1"
SCHEMA_WOE_TRANSFORM_EVIDENCE = "cardre.woe_transform_evidence.v1"
SCHEMA_WOE_TABLE = "cardre.woe_table.v1"
SCHEMA_IV_TABLE = "cardre.iv_table.v1"
SCHEMA_WOE_IV_EVIDENCE = "cardre.woe_iv_evidence.v1"
SCHEMA_VARIABLE_CLUSTERING_EVIDENCE = "cardre.variable_clustering_evidence.v1"
SCHEMA_MODEL_ARTIFACT = "cardre.model_artifact.v1"
SCHEMA_COEFFICIENT_SIGN_DIAGNOSTICS = "cardre.coefficient_sign_diagnostics.v1"
SCHEMA_SEPARATION_DIAGNOSTICS = "cardre.separation_diagnostics.v1"
SCHEMA_VIF_DIAGNOSTICS = "cardre.vif_diagnostics.v1"
SCHEMA_CALIBRATION_DIAGNOSTICS = "cardre.calibration_diagnostics.v1"
SCHEMA_SCORE_SCALING = "cardre.score_scaling.v1"
SCHEMA_VALIDATION_METRICS = "cardre.validation_metrics.v1"
SCHEMA_CUTOFF_ANALYSIS = "cardre.cutoff_analysis.v1"
SCHEMA_MANUAL_BINNING_OVERRIDES = "cardre.manual_binning_overrides.v1"
SCHEMA_FROZEN_SCORECARD_BUNDLE = "cardre.frozen_scorecard_bundle.v1"
SCHEMA_APPLY_WOE_EVIDENCE = "cardre.apply_woe_evidence.v1"
SCHEMA_APPLY_MODEL_EVIDENCE = "cardre.apply_model_evidence.v1"
SCHEMA_REPORT_BUNDLE = "cardre.report_bundle.v1"
SCHEMA_RUN_SUMMARY = "cardre.run_summary.v1"
SCHEMA_TECHNICAL_MANIFEST_INDEX = "cardre.technical_manifest_index.v1"
SCHEMA_SCORE_TABLE = "cardre.scorecard_table.v1"
SCHEMA_SCORING_EXPORT_PYTHON = "cardre.scoring_export_python.v1"
SCHEMA_SCORING_EXPORT_SQL = "cardre.scoring_export_sql.v1"
