"""Batch R3 — async dispatch, lease fencing, cancellation, concurrent-run guard.

Covers findings 2, 4 and 5 of the thermonuclear review:

1. **sync:false returns promptly** — a process-owned ThreadRunDispatcher runs
   the worker independently; the API route is not blocked on the model run.
2. **Lease fencing** — heartbeats renew during node execution (a long node is
   not terminalized as stale); cancellation arriving during the final node
   ends the run as cancelled, never succeeded; a lost lease blocks output
   persistence.
3. **Concurrent-run guard is atomic** — two submissions racing the guard
   produce exactly one run; forced submissions keep documented behaviour.

Tests use real adapters where possible and deterministic event harnesses
where a fake is unavoidable (blocking execute callables).
"""

from __future__ import annotations

import threading
import time
from datetime import UTC, datetime, timedelta

import pytest

from cardre.adapters.dispatch.thread_dispatcher import ThreadRunDispatcher
from cardre.application.execution.heartbeat import HeartbeatWatchdog
from cardre.application.ports.run_dispatcher import RunRequest
from cardre.application.runs.submit_run import SubmitRun, SubmitRunCommand
from cardre.domain.artifacts import json_logical_hash
from cardre.domain.errors import CardreError
from cardre.domain.run import RunStatus
from cardre.domain.step import StepSpec


class _BlockingHarness:
    """Runs a blocking ``execute_run`` fake with deterministic events.

    Events are created lazily on first use because run IDs are generated by
    the database at submit time, unknown to the test beforehand.
    """

    def __init__(self) -> None:
        self.executed: list[str] = []
        self.started: dict[str, threading.Event] = {}
        self.finished: dict[str, threading.Event] = {}
        self.release: dict[str, threading.Event] = {}
        self._lock = threading.Lock()

    def ensure(self, run_id: str) -> None:
        with self._lock:
            self.started.setdefault(run_id, threading.Event())
            self.finished.setdefault(run_id, threading.Event())
            self.release.setdefault(run_id, threading.Event())

    def execute(self, request) -> None:
        run_id = request.run_id
        self.ensure(run_id)
        with self._lock:
            self.executed.append(run_id)
        self.started[run_id].set()
        self.release[run_id].wait(timeout=5)
        self.finished[run_id].set()

    def wait_started(self, run_id: str, timeout: float = 5) -> None:
        self.ensure(run_id)
        assert self.started[run_id].wait(timeout), f"worker {run_id} never started"

    def wait_finished(self, run_id: str, timeout: float = 5) -> None:
        self.ensure(run_id)
        assert self.finished[run_id].wait(timeout), f"worker {run_id} never finished"


def _cmd(pv_id, *, force=False, sync=False):
    return SubmitRunCommand(
        plan_version_id=pv_id, run_scope="full_plan", force=force, sync=sync,
    )


def _noop_dispatcher():
    class _Noop:
        def dispatch(self, request):
            pass
    return _Noop()


# ---------------------------------------------------------------------------
# Finding 2 — sync:false runs asynchronously
# ---------------------------------------------------------------------------


def test_sync_false_returns_promptly_and_worker_runs_independently(provisioned_project):
    """sync=false returns with a non-terminal run while the worker is blocked."""
    project_id, uow_factory, _registry, root = provisioned_project
    with uow_factory.for_project(project_id) as uow:
        plan_id = uow.plans.create_plan(project_id, "Plan")
        pv_id = uow.plans.create_version(
            plan_id,
            [StepSpec(
                step_id="s1", node_type="cardre.noop", node_version="1",
                category="transform", params={}, params_hash=json_logical_hash({}),
                parent_step_ids=[], branch_label="", position=0, canonical_step_id="s1",
            )],
            is_committed=True,
        )
        uow.commit()

    harness = _BlockingHarness()
    dispatcher = ThreadRunDispatcher(harness.execute, max_workers=1)
    submit = SubmitRun(
        lambda: uow_factory.for_project(project_id),
        dispatcher,
        lambda cmd: harness.execute(RunRequest(cmd.run_id, pv_id, project_id)),
        None,
        governance_enabled=True,
        project_id=project_id,
    )

    start = time.monotonic()
    result = submit(_cmd(pv_id, sync=False))
    elapsed = time.monotonic() - start

    # The route returns promptly with a non-terminal run.
    assert elapsed < 1.0, f"sync=false blocked the request for {elapsed:.2f}s"
    assert result.status == "created"

    # The worker starts independently and finishes when released.
    harness.wait_started(result.run_id)
    harness.release[result.run_id].set()
    harness.wait_finished(result.run_id)
    assert harness.executed == [result.run_id]
    dispatcher.shutdown()


def test_sync_true_blocks_until_terminal(provisioned_project):
    """sync=true runs inline: the response is terminal only after completion."""
    project_id, uow_factory, _registry, root = provisioned_project
    with uow_factory.for_project(project_id) as uow:
        plan_id = uow.plans.create_plan(project_id, "Plan")
        pv_id = uow.plans.create_version(
            plan_id,
            [StepSpec(
                step_id="s1", node_type="cardre.noop", node_version="1",
                category="transform", params={}, params_hash=json_logical_hash({}),
                parent_step_ids=[], branch_label="", position=0, canonical_step_id="s1",
            )],
            is_committed=True,
        )
        uow.commit()

    harness = _BlockingHarness()
    dispatcher = ThreadRunDispatcher(harness.execute, max_workers=1)
    completed = {"value": False}

    def blocking_execute(cmd):
        harness.execute(RunRequest(cmd.run_id, pv_id, project_id))
        completed["value"] = True

    submit = SubmitRun(
        lambda: uow_factory.for_project(project_id),
        dispatcher,
        blocking_execute,
        None,
        governance_enabled=True,
        project_id=project_id,
    )

    result = submit(_cmd(pv_id, sync=True))
    assert completed["value"] is True, "sync=true returned before execution finished"
    assert result.status == "created"  # fake executor returns without terminalizing
    harness.wait_started(result.run_id)
    harness.release[result.run_id].set()
    harness.wait_finished(result.run_id)
    dispatcher.shutdown()


# ---------------------------------------------------------------------------
# Finding 4 — lease heartbeat and cancellation fencing
# ---------------------------------------------------------------------------


def test_watchdog_renews_lease_during_node_execution(provisioned_project):
    """A long-running node's heartbeat is renewed during execution, so it is
    not terminalized as stale by a subsequent submission."""
    project_id, uow_factory, _registry, root = provisioned_project
    with uow_factory.for_project(project_id) as uow:
        plan_id = uow.plans.create_plan(project_id, "Plan")
        pv_id = uow.plans.create_version(plan_id, [], is_committed=True)
        run_id = uow.runs.create(pv_id)
        uow.runs.transition(run_id, RunStatus.RUNNING,
                            expected_from=(RunStatus.CREATED, RunStatus.QUEUED))
        uow.commit()

    watchdog = HeartbeatWatchdog(
        lambda: uow_factory.for_project(project_id), run_id, interval_seconds=0.1,
    )
    watchdog.start()
    try:
        time.sleep(0.35)
    finally:
        watchdog.stop()

    with uow_factory.read_only(project_id) as uow:
        run = uow.runs.get(run_id)
    assert run is not None
    assert run.heartbeat_at is not None
    hb_ts = datetime.fromisoformat(run.heartbeat_at.replace("Z", "+00:00"))
    age = datetime.now(UTC) - hb_ts
    assert age < timedelta(seconds=1), f"heartbeat not renewed during node: age={age}"


def test_cancellation_during_final_node_ends_cancelled(provisioned_project):
    """A cancellation arriving while the final node runs must end the run as
    cancelled, never succeeded."""
    project_id, uow_factory, _registry, root = provisioned_project
    with uow_factory.for_project(project_id) as uow:
        plan_id = uow.plans.create_plan(project_id, "Plan")
        pv_id = uow.plans.create_version(
            plan_id,
            [StepSpec(
                step_id="s1", node_type="cardre.noop", node_version="1",
                category="transform", params={}, params_hash=json_logical_hash({}),
                parent_step_ids=[], branch_label="", position=0, canonical_step_id="s1",
            )],
            is_committed=True,
        )
        run_id = uow.runs.create(pv_id)  # status = created; ExecuteRun claims RUNNING
        uow.commit()

    from cardre.application.runs.execute_run import ExecuteRun, ExecuteRunCommand
    from cardre.application.runs.finalize_run import FinalizeRun
    from cardre.domain.run import RunStepStatus

    finalize = FinalizeRun(
        lambda: uow_factory.for_project(project_id),
        type("Pub", (), {"publish": lambda self, run_id, payload: None})(),
    )

    class _BlockingRunner:
        def run_step(self, *args, **kwargs):
            # Block to simulate a long final node; cancellation is set meanwhile.
            time.sleep(0.3)
            from cardre.application.execution.step_runner import StepExecutionResult
            return StepExecutionResult(
                step_id="s1", node_type="cardre.noop", status=RunStepStatus.SUCCEEDED,
                fingerprint={}, input_artifact_ids=[], output_artifact_ids=[],
                staged_artifacts=[],
            )

    class _NoopCatalogue:
        def availability(self, node_type):
            return type("Av", (), {"available": True})()

    executor = ExecuteRun(
        lambda: uow_factory.for_project(project_id),
        _NoopCatalogue(),
        _BlockingRunner(),
        finalize,
        lambda: type("Store", (), {"finalize": lambda self, s: None, "object_path": lambda self, h: ""})(),
        heartbeat_interval_seconds=0.1,
    )

    from cardre.application.runs.cancel_run import CancelRun, CancelRunCommand
    thread = threading.Thread(target=lambda: executor(ExecuteRunCommand(run_id=run_id)))
    thread.start()
    time.sleep(0.15)  # let the node block
    CancelRun(lambda: uow_factory.for_project(project_id))(CancelRunCommand(run_id=run_id))
    thread.join(timeout=5)

    with uow_factory.read_only(project_id) as uow:
        run = uow.runs.get(run_id)
    assert run is not None
    assert str(run.status) == "cancelled", f"final status: {run.status}"


def test_lost_lease_blocks_output_persistence(provisioned_project):
    """A worker whose lease was lost (run terminalized as stale) must not
    persist output after the recovery."""
    project_id, uow_factory, _registry, root = provisioned_project
    with uow_factory.for_project(project_id) as uow:
        plan_id = uow.plans.create_plan(project_id, "Plan")
        pv_id = uow.plans.create_version(
            plan_id,
            [StepSpec(
                step_id="s1", node_type="cardre.noop", node_version="1",
                category="transform", params={}, params_hash=json_logical_hash({}),
                parent_step_ids=[], branch_label="", position=0, canonical_step_id="s1",
            )],
            is_committed=True,
        )
        run_id = uow.runs.create(pv_id)  # status = created; ExecuteRun claims RUNNING
        uow.commit()

    from cardre.application.runs.execute_run import ExecuteRun, ExecuteRunCommand
    from cardre.application.runs.finalize_run import FinalizeRun
    from cardre.domain.run import RunStepStatus

    finalize = FinalizeRun(
        lambda: uow_factory.for_project(project_id),
        type("Pub", (), {"publish": lambda self, run_id, payload: None})(),
    )

    class _BlockingRunner:
        def run_step(self, *args, **kwargs):
            time.sleep(0.2)
            from cardre.application.execution.step_runner import StepExecutionResult
            return StepExecutionResult(
                step_id="s1", node_type="cardre.noop", status=RunStepStatus.SUCCEEDED,
                fingerprint={}, input_artifact_ids=[], output_artifact_ids=[],
                staged_artifacts=[],
            )

    class _NoopCatalogue:
        def availability(self, node_type):
            return type("Av", (), {"available": True})()

    persisted = {"count": 0}

    class _CountingStore:
        def finalize(self, staged):
            persisted["count"] += 1

    executor = ExecuteRun(
        lambda: uow_factory.for_project(project_id),
        _NoopCatalogue(),
        _BlockingRunner(),
        finalize,
        lambda: _CountingStore(),
        heartbeat_interval_seconds=0.1,
    )

    thread = threading.Thread(target=lambda: executor(ExecuteRunCommand(run_id=run_id)))
    thread.start()
    time.sleep(0.1)
    # Lease lost: terminalize the run as interrupted (stale recovery).
    with uow_factory.for_project(project_id) as uow:
        uow.runs.transition(run_id, RunStatus.INTERRUPTED,
                            expected_from=(RunStatus.RUNNING,))
        uow.commit()
    thread.join(timeout=5)

    # After lease loss, the worker must not have persisted any output.
    assert persisted["count"] == 0, "worker persisted output after lease loss"
    with uow_factory.read_only(project_id) as uow:
        run = uow.runs.get(run_id)
    assert str(run.status) == RunStatus.INTERRUPTED.value


# ---------------------------------------------------------------------------
# Finding 5 — concurrent-run guard is atomic
# ---------------------------------------------------------------------------


def test_concurrent_guard_two_threads_exactly_one_run(provisioned_project):
    """Two submissions racing the guard produce exactly one run; the other
    gets the concurrent-run error."""
    project_id, uow_factory, _registry, root = provisioned_project
    with uow_factory.for_project(project_id) as uow:
        plan_id = uow.plans.create_plan(project_id, "Plan")
        pv_id = uow.plans.create_version(plan_id, [], is_committed=True)
        uow.commit()

    barrier = threading.Barrier(2)
    results: list[dict] = []
    lock = threading.Lock()

    def attempt():
        submit = SubmitRun(
            lambda: uow_factory.for_project(project_id),
            _noop_dispatcher(), lambda cmd: None, None,
            governance_enabled=True, project_id=project_id,
        )
        barrier.wait()
        try:
            res = submit(_cmd(pv_id, sync=False))
            with lock:
                results.append({"ok": True, "run_id": res.run_id})
        except CardreError as exc:
            with lock:
                results.append({"ok": False, "code": exc.code})

    t1 = threading.Thread(target=attempt)
    t2 = threading.Thread(target=attempt)
    t1.start()
    t2.start()
    t1.join(timeout=5)
    t2.join(timeout=5)

    ok = [r for r in results if r["ok"]]
    errs = [r for r in results if not r["ok"]]
    assert len(ok) == 1, f"expected exactly one success, got {results}"
    assert len(errs) == 1
    assert errs[0]["code"] == "CONCURRENT_RUN"

    with uow_factory.read_only(project_id) as uow:
        runs = uow.runs.list_for_plan_version(pv_id)
    active = [r for r in runs if r.status in ("created", "queued", "running") and not r.force]
    assert len(active) == 1, "never more than one active non-forced run"


def test_concurrent_guard_force_remains_allowed(provisioned_project):
    """force=true is allowed even when an active non-forced run exists."""
    project_id, uow_factory, _registry, root = provisioned_project
    with uow_factory.for_project(project_id) as uow:
        plan_id = uow.plans.create_plan(project_id, "Plan")
        pv_id = uow.plans.create_version(plan_id, [], is_committed=True)
        uow.commit()

    submit = SubmitRun(
        lambda: uow_factory.for_project(project_id),
        _noop_dispatcher(), lambda cmd: None, None,
        governance_enabled=True, project_id=project_id,
    )
    r1 = submit(_cmd(pv_id, sync=False))
    with pytest.raises(CardreError) as exc:
        submit(_cmd(pv_id, force=False))
    assert exc.value.code == "CONCURRENT_RUN"

    r2 = submit(_cmd(pv_id, force=True))
    assert r2.run_id != r1.run_id

    with uow_factory.read_only(project_id) as uow:
        runs = uow.runs.list_for_plan_version(pv_id)
    non_forced_active = [
        r for r in runs if r.status in ("created", "queued", "running") and not r.force
    ]
    assert len(non_forced_active) == 1


def test_partial_unique_index_exists(provisioned_project):
    """The schema has a partial unique index enforcing one active non-forced run."""
    project_id, uow_factory, _registry, root = provisioned_project
    with uow_factory.read_only(project_id) as uow:
        rows = uow._conn.execute(
            "SELECT name, sql FROM sqlite_master WHERE type='index' AND name=?",
            ("idx_runs_one_active_non_forced",),
        ).fetchall()
    assert len(rows) == 1
    assert "WHERE force = 0" in rows[0]["sql"]
    assert "created" in rows[0]["sql"] and "running" in rows[0]["sql"]
