"""Unit of work port — transaction boundary for persistence."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol, runtime_checkable

from cardre.domain.artifacts import ArtifactRef
from cardre.domain.evidence import EvidenceArtifact, EvidenceEdge
from cardre.domain.plan import Plan, PlanVersion
from cardre.domain.project import Project
from cardre.domain.run import Run, RunStatus, RunStep
from cardre.domain.step import StepSpec


@runtime_checkable
class ProjectRepoPort(Protocol):
    def create(self, name: str) -> str: ...
    def get(self, project_id: str) -> Project | None: ...
    def list_all(self) -> list[Project]: ...


@runtime_checkable
class PlanRepoPort(Protocol):
    def create_plan(self, project_id: str, name: str) -> str: ...
    def get_plan(self, plan_id: str) -> Plan | None: ...
    def list_for_project(self, project_id: str) -> list[Plan]: ...
    def create_version(self, plan_id: str, steps: list[StepSpec] | None = None,
                       description: str = "", *, is_committed: bool = False) -> str: ...
    def get_version(self, plan_version_id: str) -> PlanVersion | None: ...
    def get_version_steps(self, plan_version_id: str) -> list[StepSpec]: ...
    def list_versions(self, plan_id: str) -> list[PlanVersion]: ...
    def get_latest_version_id(self, plan_id: str) -> str | None: ...
    def get_plan_id_for_version(self, plan_version_id: str) -> str | None: ...
    def update_version_description(self, plan_version_id: str, description: str) -> None: ...
    def commit_version(self, plan_version_id: str) -> None: ...


@runtime_checkable
class StepRepoPort(Protocol):
    def get_steps(self, plan_version_id: str) -> list[StepSpec]: ...
    def insert_steps_and_edges(self, plan_version_id: str, steps: list[StepSpec]) -> None: ...
    def get_parent_edges(self, plan_version_id: str, child_step_id: str) -> list[dict[str, Any]]: ...
    def get_child_edges(self, plan_version_id: str, parent_step_id: str) -> list[dict[str, Any]]: ...
    def get_all_edges(self, plan_version_id: str) -> list[dict[str, Any]]: ...
    def get_distinct_node_types(self, project_id: str) -> list[dict[str, Any]]: ...


@runtime_checkable
class RunRepoPort(Protocol):
    def create(self, plan_version_id: str, run_scope: str = "full_plan",
               branch_id: str | None = None, force: bool = False,
               requested_by: str | None = None, request_id: str | None = None) -> str: ...
    def get(self, run_id: str) -> Run | None: ...
    def transition(self, run_id: str, to_status: RunStatus, *,
                   expected_from: tuple[RunStatus, ...] = (RunStatus.RUNNING,)) -> bool: ...
    def heartbeat(self, run_id: str) -> None: ...
    def set_active_step(self, run_id: str, step_id: str | None) -> None: ...
    def get_active_step(self, run_id: str) -> str | None: ...
    def append_diagnostic(self, run_id: str, diagnostic: dict[str, Any]) -> None: ...
    def get_diagnostics(self, run_id: str) -> list[dict[str, Any]]: ...
    def list_for_plan_version(self, plan_version_id: str | None = None) -> list[Run]: ...
    def list_for_project(self, project_id: str) -> list[Run]: ...
    def get_latest_successful_id(self, plan_version_id: str, branch_id: str | None = None) -> str | None: ...
    def get_latest_successful_id_for_plan(self, plan_id: str) -> str | None: ...
    def get_latest_successful_step_across_plan(self, plan_id: str, step_id: str, branch_id: str | None = None) -> RunStep | None: ...
    def set_cancel_requested(self, run_id: str) -> None: ...


@runtime_checkable
class RunStepRepoPort(Protocol):
    def insert(self, run_step: RunStep) -> None: ...
    def get(self, run_step_id: str) -> RunStep | None: ...
    def get_for_run(self, run_id: str) -> list[RunStep]: ...
    def get_latest_successful_step(self, plan_version_id: str, step_id: str, branch_id: str | None = None) -> RunStep | None: ...


@runtime_checkable
class ArtifactRepoPort(Protocol):
    def register(self, artifact: ArtifactRef) -> str: ...
    def get(self, artifact_id: str) -> ArtifactRef | None: ...
    def get_for_project(self, project_id: str, artifact_id: str) -> ArtifactRef | None: ...
    def list_for_project(self, project_id: str, *, role: str | None = None,
                         artifact_type: str | None = None, limit: int = 100, offset: int = 0) -> list[ArtifactRef]: ...
    def register_lineage(self, run_id: str, run_step_id: str, plan_version_id: str,
                         step_id: str, artifact_id: str, direction: str, branch_id: str | None = None) -> None: ...
    def output_artifact_ids_for_run_step(self, run_step_id: str) -> list[str]: ...
    def output_artifacts_for_run_step(self, run_step_id: str) -> list[ArtifactRef]: ...
    def output_artifact_ids_for_run(self, run_id: str) -> list[str]: ...


@runtime_checkable
class EvidenceRepoPort(Protocol):
    def insert_edge(self, edge: EvidenceEdge) -> None: ...
    def insert_artifact(self, artifact: EvidenceArtifact) -> None: ...
    def get_edges_for_run_step(self, run_step_id: str) -> list[EvidenceEdge]: ...
    def get_edges_for_run(self, run_id: str) -> list[EvidenceEdge]: ...
    def get_edges_for_plan_step(self, plan_version_id: str, step_id: str) -> list[EvidenceEdge]: ...
    def get_edges_for_plan_step_branch(self, plan_version_id: str, step_id: str, branch_id: str | None) -> list[EvidenceEdge]: ...
    def get_artifacts_for_edge(self, evidence_edge_id: str) -> list[EvidenceArtifact]: ...
    def get_artifacts_for_run_step(self, run_step_id: str) -> list[EvidenceArtifact]: ...
    def list_for_run_ordered(self, run_id: str) -> list[tuple[EvidenceEdge, list[EvidenceArtifact]]]: ...


@runtime_checkable
class UnitOfWork(Protocol):
    @property
    def projects(self) -> ProjectRepoPort: ...
    @property
    def plans(self) -> PlanRepoPort: ...
    @property
    def steps(self) -> StepRepoPort: ...
    @property
    def runs(self) -> RunRepoPort: ...
    @property
    def run_steps(self) -> RunStepRepoPort: ...
    @property
    def artifacts(self) -> ArtifactRepoPort: ...
    @property
    def evidence(self) -> EvidenceRepoPort: ...

    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> UnitOfWork: ...
    def __exit__(self, *exc: object) -> None: ...


@runtime_checkable
class UnitOfWorkFactory(Protocol):
    def for_project(self, project_id: str) -> UnitOfWork: ...
    def for_root(self, root: Path) -> UnitOfWork: ...
    def read_only(self, project_id: str) -> UnitOfWork: ...
    def for_root_readonly(self, root: Path) -> UnitOfWork: ...
