"""Unit of work port — transaction boundary for persistence."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol, runtime_checkable

from cardre.domain.artifacts import ArtifactRef
from cardre.domain.diagnostics import JsonDict
from cardre.domain.evidence import EvidenceArtifact, EvidenceEdge
from cardre.domain.plan import Plan, PlanVersion
from cardre.domain.project import Project
from cardre.domain.run import Run, RunStatus, RunStep
from cardre.domain.step import StepSpec


@runtime_checkable
class ProjectRepoPort(Protocol):
    def create(self, name: str) -> str: ...
    def get(self, project_id: str) -> Project | None: ...
    def list_all(self) -> list[Project]: ...


@runtime_checkable
class PlanRepoPort(Protocol):
    def create_plan(self, project_id: str, name: str) -> str: ...
    def get_plan(self, plan_id: str) -> Plan | None: ...
    def list_for_project(self, project_id: str) -> list[Plan]: ...
    def create_version(self, plan_id: str, steps: list[StepSpec] | None = None,
                       description: str = "", *, is_committed: bool = False) -> str: ...
    def get_version(self, plan_version_id: str) -> PlanVersion | None: ...
    def get_version_steps(self, plan_version_id: str) -> list[StepSpec]: ...
    def list_versions(self, plan_id: str) -> list[PlanVersion]: ...
    def get_latest_version_id(self, plan_id: str) -> str | None: ...
    def get_plan_id_for_version(self, plan_version_id: str) -> str | None: ...
    def update_version_description(self, plan_version_id: str, description: str) -> None: ...
    def commit_version(self, plan_version_id: str) -> None: ...
    def update_step_params(self, plan_version_id: str, step_id: str,
                           params: dict[str, Any], params_hash: str) -> None: ...


@runtime_checkable
class StepRepoPort(Protocol):
    def get_steps(self, plan_version_id: str) -> list[StepSpec]: ...
    def insert_steps_and_edges(self, plan_version_id: str, steps: list[StepSpec]) -> None: ...
    def get_parent_edges(self, plan_version_id: str, child_step_id: str) -> list[dict[str, Any]]: ...
    def get_child_edges(self, plan_version_id: str, parent_step_id: str) -> list[dict[str, Any]]: ...
    def get_all_edges(self, plan_version_id: str) -> list[dict[str, Any]]: ...
    def get_distinct_node_types(self, project_id: str) -> list[dict[str, Any]]: ...


@runtime_checkable
class RunRepoPort(Protocol):
    def create(self, plan_version_id: str, run_scope: str = "full_plan",
               force: bool = False,
               requested_by: str | None = None, request_id: str | None = None,
               metadata: dict[str, Any] | None = None) -> str: ...
    def create_if_no_active_run(self, plan_version_id: str, run_scope: str = "full_plan",
                                force: bool = False,
                                requested_by: str | None = None, request_id: str | None = None) -> str | None: ...
    def get(self, run_id: str) -> Run | None: ...
    def transition(self, run_id: str, to_status: RunStatus, *,
                   expected_from: tuple[RunStatus, ...] = (RunStatus.RUNNING,)) -> bool: ...
    def transition_success(self, run_id: str, worker_generation: int) -> bool: ...
    def transition_interrupted(self, run_id: str, observed_heartbeat_at: str | None) -> bool: ...
    def begin_worker_generation(self, run_id: str) -> int: ...
    def claim_running_lease(self, run_id: str) -> int: ...
    def assert_running_lease(self, run_id: str, generation: int) -> None: ...
    def heartbeat(self, run_id: str) -> None: ...
    def set_active_step(self, run_id: str, step_id: str | None) -> None: ...
    def get_active_step(self, run_id: str) -> str | None: ...
    def append_diagnostic(self, run_id: str, diagnostic: dict[str, Any]) -> None: ...
    def get_diagnostics(self, run_id: str) -> list[dict[str, Any]]: ...
    def get_diagnostics_for_project(self, project_id: str) -> list[dict[str, Any]]: ...
    def list_for_plan_version(self, plan_version_id: str | None = None) -> list[Run]: ...
    def list_for_project(self, project_id: str) -> list[Run]: ...
    def get_latest_successful_id(self, plan_version_id: str) -> str | None: ...
    def get_latest_successful_id_for_plan(self, plan_id: str) -> str | None: ...
    def get_latest_successful_step_across_plan(self, plan_id: str, step_id: str) -> RunStep | None: ...
    def list_successful_steps_across_plan_ordered(self, plan_id: str, step_id: str) -> list[RunStep]: ...
    def set_cancel_requested(self, run_id: str) -> None: ...


@runtime_checkable
class RunStepRepoPort(Protocol):
    def insert(self, run_step: RunStep) -> None: ...
    def get(self, run_step_id: str) -> RunStep | None: ...
    def get_for_run(self, run_id: str) -> list[RunStep]: ...
    def get_for_project(self, project_id: str) -> list[RunStep]: ...
    def get_latest_successful_step(self, plan_version_id: str, step_id: str) -> RunStep | None: ...
    def list_successful_steps_ordered(self, plan_version_id: str, step_id: str) -> list[RunStep]: ...


@runtime_checkable
class ArtifactRepoPort(Protocol):
    def register(self, artifact: ArtifactRef) -> str: ...
    def get_blob(self, physical_hash: str) -> dict[str, Any] | None: ...
    def get(self, artifact_id: str) -> ArtifactRef | None: ...
    def get_for_project(self, project_id: str, artifact_id: str) -> ArtifactRef | None: ...
    def list_for_project(self, project_id: str, *, role: str | None = None,
                         artifact_type: str | None = None, limit: int = 100, offset: int = 0) -> list[ArtifactRef]: ...
    def register_lineage(self, run_id: str, run_step_id: str, plan_version_id: str,
                         step_id: str, artifact_id: str, direction: str) -> None: ...
    def output_artifact_ids_for_run_step(self, run_step_id: str) -> list[str]: ...
    def output_artifacts_for_run_step(self, run_step_id: str) -> list[ArtifactRef]: ...
    def output_artifact_ids_for_run(self, run_id: str) -> list[str]: ...
    def artifacts_for_run_step(self, run_step_id: str) -> list[tuple[str, ArtifactRef]]: ...


@runtime_checkable
class EvidenceRepoPort(Protocol):
    def insert_edge(self, edge: EvidenceEdge) -> None: ...
    def insert_artifact(self, artifact: EvidenceArtifact) -> None: ...
    def get_edges_for_run_step(self, run_step_id: str) -> list[EvidenceEdge]: ...
    def get_edges_for_run(self, run_id: str) -> list[EvidenceEdge]: ...
    def get_edges_for_plan_step(self, plan_version_id: str, step_id: str) -> list[EvidenceEdge]: ...
    def get_artifacts_for_edge(self, evidence_edge_id: str) -> list[EvidenceArtifact]: ...
    def get_artifacts_for_run_step(self, run_step_id: str) -> list[EvidenceArtifact]: ...
    def list_for_run_ordered(self, run_id: str) -> list[tuple[EvidenceEdge, list[EvidenceArtifact]]]: ...


@runtime_checkable
class PublicationRepoPort(Protocol):
    def enqueue_artifact(self, run_id: str, plan_version_id: str, run_step_id: str,
                         artifact_id: str, physical_hash: str, storage_key: str,
                         staging_source: str) -> str: ...
    def enqueue_manifest(self, run_id: str, plan_version_id: str,
                         payload: JsonDict, manifest_hash: str) -> str: ...
    def mark_published(self, outbox_id: str) -> None: ...
    def mark_failed(self, outbox_id: str, error: str) -> None: ...
    def get(self, outbox_id: str) -> dict[str, Any] | None: ...
    def list_by_run(self, run_id: str) -> list[dict[str, Any]]: ...
    def list_pending(self, limit: int = 1000) -> list[dict[str, Any]]: ...


@runtime_checkable
class DispatchRepoPort(Protocol):
    """Durable run-dispatch queue: committed with run creation, drained on
    claim, reconciled on startup."""

    def enqueue(self, run_id: str) -> None: ...
    def claim(self, run_id: str) -> bool: ...
    def list_pending(self) -> list[str]: ...
    def remove(self, run_id: str) -> None: ...


@runtime_checkable
class ReadOnlyUnitOfWork(Protocol):
    """Read-only persistence boundary.

    Exposes repository query objects without commit/rollback semantics, so a
    query use case cannot silently begin a write transaction or persist
    mutations. ``close()`` (or the context manager) releases the connection.
    """

    @property
    def projects(self) -> ProjectRepoPort: ...
    @property
    def plans(self) -> PlanRepoPort: ...
    @property
    def steps(self) -> StepRepoPort: ...
    @property
    def runs(self) -> RunRepoPort: ...
    @property
    def run_steps(self) -> RunStepRepoPort: ...
    @property
    def artifacts(self) -> ArtifactRepoPort: ...
    @property
    def evidence(self) -> EvidenceRepoPort: ...
    @property
    def publications(self) -> PublicationRepoPort: ...
    @property
    def dispatches(self) -> DispatchRepoPort: ...

    @property
    def reports(self) -> Any: ...

    @property
    def exports(self) -> Any: ...

    def close(self) -> None: ...
    def __enter__(self) -> ReadOnlyUnitOfWork: ...
    def __exit__(self, *exc: object) -> None: ...


@runtime_checkable
class UnitOfWork(ReadOnlyUnitOfWork, Protocol):
    """Mutation persistence boundary.

    Every mutation is performed inside one explicit transaction that is begun
    when the UoW is constructed. ``commit()`` makes the transaction durable;
    ``rollback()`` discards it; ``close()`` rolls back any uncommitted work and
    releases the connection.
    """

    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def __enter__(self) -> UnitOfWork: ...
    def __exit__(self, *exc: object) -> None: ...


@runtime_checkable
class UnitOfWorkFactory(Protocol):
    def for_project(self, project_id: str) -> UnitOfWork: ...
    def for_root(self, root: Path) -> UnitOfWork: ...
    def read_only(self, project_id: str) -> ReadOnlyUnitOfWork: ...
    def for_root_readonly(self, root: Path) -> ReadOnlyUnitOfWork: ...
